import { steps } from '#src/stage/choreography.ts';

// Three Continues, three fees, and the advertised number left behind. Then the all in
// version shows the same lines on its first screen. The pass ends on the mount state,
// which is the one the subject's pose requires (SPEC §6, §8).
export default steps([
  { assert: { selector: '[data-part=total][data-mode="dripping"][data-step="0"]', state: 'visible' } },
  { assert: { selector: '[data-part=fee-0]', state: 'hidden' } },
  { wait: 500 },
  { moveTo: '[data-part=next]' },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=fee-0]', state: 'visible' } },
  { assert: { selector: '[data-part=fee-1]', state: 'hidden' } },
  { wait: 700 },
  { moveTo: '[data-part=next]' },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=fee-1]', state: 'visible' } },
  { wait: 700 },
  { moveTo: '[data-part=next]' },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=total][data-step="3"]', state: 'visible' } },
  { assert: { selector: '[data-part=fee-2]', state: 'visible' } },
  { wait: 1100 },
  { moveTo: '[data-part=mode-honest]' },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=total][data-mode="honest"][data-step="0"]', state: 'visible' } },
  { assert: { selector: '[data-part=fee-2]', state: 'visible' } },
  { wait: 1300 },
  { moveTo: '[data-part=mode-dripping]' },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=total][data-mode="dripping"][data-step="0"]', state: 'visible' } },
  { assert: { selector: '[data-part=fee-0]', state: 'hidden' } },
  { wait: 800 },
]);
