import { prefersReducedMotion } from '#src/kit/motion.ts';
import { part } from '#src/kit/parts.ts';
import type { DemoClock } from '#src/stage/clock.ts';

const ARENA_W = 360;
const TILE = 30;
const TRAVEL = ARENA_W - TILE;
const ARENA_H = 124;
const DURATION_MS = 1800;

/**
 * The four pinned points, written once and used three ways: as the animation's
 * keyframes, as the ghost poses drawn where each pin sits, and as the ticks on the
 * timeline below. `offset` is both the moment and the horizontal position, so a pin's
 * ghost stands directly over the tick that schedules it, and the only values left to
 * read are the ones that make the motion a shape rather than a slide.
 *
 * `easing` is the curve *leaving* that pin, which is how CSS and the Web Animations
 * API both read it.
 */
type Stop = { offset: number; y: number; rot: number; easing?: string };

const LAST: Stop = { offset: 1, y: -86, rot: 270 };

const STOPS: Stop[] = [
  { offset: 0, y: 0, rot: 0, easing: 'ease-out' },
  { offset: 0.3, y: -64, rot: 90, easing: 'ease-in-out' },
  { offset: 0.62, y: -24, rot: 180, easing: 'ease-out' },
  LAST,
];

const pose = (stop: Stop) => `translate(${(stop.offset * TRAVEL).toFixed(1)}px, ${stop.y}px) rotate(${stop.rot}deg)`;

const frames = (): Keyframe[] => STOPS.map((stop) => ({ offset: stop.offset, easing: stop.easing, transform: pose(stop) }));

/**
 * Keyframe specimen: one tile run through a four-stop timeline, with the stops
 * themselves drawn twice so the term is visible when nothing is moving. Each pin has a
 * ghost at the pose it holds and a tick at the moment it holds it; everything between
 * the ghosts is generated by interpolation, which is the claim the term makes.
 *
 * The subject is the animated tile, not the diagram: the diagram is scenery that says
 * where the pins are, and the term names the thing whose values are being pinned.
 *
 * `element.animate` is out of reach of `motion.css`, so the demo asks
 * `prefersReducedMotion` itself and parks the tile on the last pin instead of playing
 * (SPEC §5). `data-settled` is timed on the stage's clock so a pose cannot let the run
 * finish underneath a reader inspecting it (SPEC §6).
 */
export function mount(root: HTMLElement, clock: DemoClock): void {
  const ghosts = STOPS.map(
    (stop) => `
      <span
        style="position: absolute; left: 0; bottom: 0; width: ${TILE}px; height: ${TILE}px; border-radius: 7px;
               border: 1px dashed var(--sp-accent); transform: ${pose(stop)}"
      ></span>`,
  ).join('');

  const ticks = STOPS.map(
    (stop) => `
      <span
        style="position: absolute; top: 0; left: ${(TILE / 2 + stop.offset * TRAVEL).toFixed(1)}px; transform: translateX(-50%);
               display: flex; flex-direction: column; align-items: center; gap: 5px"
      >
        <span style="width: 7px; height: 7px; border-radius: 50%; background: var(--sp-accent)"></span>
        <span class="sp-label" style="font-size: 11px">${Math.round(stop.offset * 100)}%</span>
      </span>`,
  ).join('');

  root.innerHTML = `
    <div class="sp-app">
      <div class="sp-window" data-part="panel" style="width: 400px">
        <div class="sp-row sp-row--between sp-context">
          <span class="sp-heading">Four pinned stops</span>
          <button class="sp-button sp-button--ghost sp-button--sm" type="button" data-part="replay">Replay</button>
        </div>
        <div style="position: relative; width: ${ARENA_W}px; height: ${ARENA_H}px; margin-top: 10px">
          <div class="sp-context" style="position: absolute; inset: 0; pointer-events: none">${ghosts}</div>
          <span
            data-part="tile"
            data-subject
            style="position: absolute; left: 0; bottom: 0; width: ${TILE}px; height: ${TILE}px; border-radius: 7px;
                   background: var(--sp-accent); transform: ${pose(LAST)}"
          ></span>
        </div>
        <div class="sp-context" style="position: relative; width: ${ARENA_W}px; height: 30px; margin-top: 8px">
          <span style="position: absolute; top: 3px; left: ${TILE / 2}px; right: ${TILE / 2}px; height: 1px; background: var(--sp-line)"></span>
          ${ticks}
        </div>
        <p class="sp-text sp-context" style="margin: 6px 0 0">
          The dashed poses are pinned. Every frame between them is generated.
        </p>
      </div>
    </div>
  `;

  const panel = part(root, 'panel');
  const tile = part(root, 'tile');
  let settling: number | undefined;

  const settle = () => {
    panel.removeAttribute('data-running');
    panel.setAttribute('data-settled', '');
  };

  const play = () => {
    clock.clearTimeout(settling);
    panel.removeAttribute('data-settled');
    panel.setAttribute('data-running', '');
    for (const animation of tile.getAnimations()) animation.cancel();

    if (prefersReducedMotion(root)) {
      settle();
      return;
    }

    tile.animate(frames(), { duration: DURATION_MS, fill: 'forwards' });
    settling = clock.setTimeout(settle, DURATION_MS + 60);
  };

  part(root, 'replay').addEventListener('click', play);
}
