import { steps } from '#src/stage/choreography.ts';

// The whole way out, click by click, and then the same job on the honest route. Each
// control reaches a named screen rather than flipping the one it finds (SPEC §8).
export default steps([
  { wait: 500 },
  { assert: { selector: '[data-part=path][data-route=obstructed][data-step="0"]', state: 'visible' } },
  { assert: { selector: '[data-part=hurdle-1]', state: 'visible' } },
  { moveTo: '[data-part=hurdle-1]' },
  { wait: 350 },
  { click: true },
  { wait: 550 },
  // Screen two is a preferences list, and the way out is the smallest line on it.
  { assert: { selector: '[data-part=path][data-step="1"]', state: 'visible' } },
  { assert: { selector: '[data-part=hurdle-2]', state: 'visible' } },
  { wait: 700 },
  { moveTo: '[data-part=hurdle-2]' },
  { wait: 350 },
  { click: true },
  { wait: 550 },
  { assert: { selector: '[data-part=path][data-step="2"]', state: 'visible' } },
  { assert: { selector: '[data-part=keep]', state: 'visible' } },
  { assert: { selector: '[data-part=hurdle-3]', state: 'visible' } },
  { wait: 800 },
  { moveTo: '[data-part=hurdle-3]' },
  { wait: 350 },
  { click: true },
  { wait: 550 },
  { assert: { selector: '[data-part=path][data-step="3"]', state: 'visible' } },
  { assert: { selector: '[data-part=deadend]', state: 'visible' } },
  { wait: 1500 },
  { moveTo: '[data-part=route-direct]' },
  { wait: 350 },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=path][data-route=direct][data-step="0"]', state: 'visible' } },
  { assert: { selector: '[data-part=cancel-now]', state: 'visible' } },
  { assert: { selector: '[data-part=hurdle-1]', state: 'hidden' } },
  { wait: 500 },
  { moveTo: '[data-part=cancel-now]' },
  { wait: 350 },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=path][data-route=direct][data-step="1"]', state: 'visible' } },
  { assert: { selector: '[data-part=done]', state: 'visible' } },
  { wait: 1500 },
]);
