import { steps } from '#src/stage/choreography.ts';

// Build one clause from menus, type its value, add a second clause, then change the join.
// Every claim lands on a trigger, the rule, or the count, never inside a menu a pick closed.
export default steps([
  { wait: 700 },
  { assert: { selector: '[data-part=rule][data-clauses="1"]', state: 'visible' } },
  { assert: { selector: '[data-part=count][data-hits="12"]', state: 'visible' } },
  { assert: { selector: '[data-part=clause-2]', state: 'hidden' } },
  { wait: 500 },

  { moveTo: '[data-part=field-1]' },
  { wait: 250 },
  { click: true },
  { wait: 450 },
  { assert: { selector: '[data-part=fieldmenu-1][data-open]', state: 'visible' } },
  { moveTo: '[data-part=f-1-rating]' },
  { wait: 250 },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=field-1][data-field=rating]', state: 'visible' } },
  { wait: 400 },

  { moveTo: '[data-part=op-1]' },
  { wait: 250 },
  { click: true },
  { wait: 450 },
  { moveTo: '[data-part=o-1-atleast]' },
  { wait: 250 },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=op-1][data-op=atleast]', state: 'visible' } },
  { wait: 400 },

  { moveTo: '[data-part=value-1]' },
  { click: true },
  { wait: 250 },
  { type: '4' },
  { wait: 500 },
  { assert: { selector: '[data-part=count][data-hits="7"]', state: 'visible' } },
  { wait: 900 },

  { moveTo: '[data-part=add]' },
  { wait: 250 },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=rule][data-clauses="2"]', state: 'visible' } },
  { assert: { selector: '[data-part=clause-2]', state: 'visible' } },
  { assert: { selector: '[data-part=join]', state: 'visible' } },
  { wait: 400 },

  { moveTo: '[data-part=field-2]' },
  { wait: 250 },
  { click: true },
  { wait: 450 },
  { moveTo: '[data-part=f-2-plays]' },
  { wait: 250 },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=field-2][data-field=plays]', state: 'visible' } },
  { wait: 350 },

  { moveTo: '[data-part=op-2]' },
  { wait: 250 },
  { click: true },
  { wait: 450 },
  { moveTo: '[data-part=o-2-atleast]' },
  { wait: 250 },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=op-2][data-op=atleast]', state: 'visible' } },
  { wait: 350 },

  { moveTo: '[data-part=value-2]' },
  { click: true },
  { wait: 250 },
  { type: '12' },
  { wait: 600 },
  // Two clauses joined by and: the tighter rule matches fewer tracks.
  { assert: { selector: '[data-part=count][data-hits="5"]', state: 'visible' } },
  { wait: 1000 },

  { moveTo: '[data-part=join-or]' },
  { wait: 250 },
  { click: true },
  { wait: 600 },
  // The same two clauses, joined the other way.
  { assert: { selector: '[data-part=count][data-hits="9"]', state: 'visible' } },
  { wait: 1200 },

  { moveTo: '[data-part=join-and]' },
  { wait: 250 },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=count][data-hits="5"]', state: 'visible' } },
  { wait: 900 },
]);
