import { steps } from '#src/stage/choreography.ts';

// The width is set absolutely at each stop and the count is read back from the nav, so the
// claim being proved is the arithmetic: five fit, then two, then one, with the same items
// falling into More in rank order. Choosing a page from the menu is checked on the trigger,
// not inside the menu the choice just closed (SPEC §8).
export default steps([
  { wait: 700 },
  { assert: { selector: '[data-part=nav][data-visible="5"]', state: 'visible' } },
  { assert: { selector: '[data-part=item-5]', state: 'visible' } },
  { assert: { selector: '[data-part=more]', state: 'hidden' } },
  { wait: 700 },
  { moveTo: '[data-part=pick-medium]' },
  { click: true },
  { wait: 700 },
  { assert: { selector: '[data-part=nav][data-visible="2"]', state: 'visible' } },
  { assert: { selector: '[data-part=item-2]', state: 'visible' } },
  { assert: { selector: '[data-part=item-5]', state: 'hidden' } },
  { assert: { selector: '[data-part=more]', state: 'visible' } },
  { wait: 800 },
  { moveTo: '[data-part=more]' },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=menu]', state: 'visible' } },
  { assert: { selector: '[data-part=item-3]', state: 'visible' } },
  { assert: { selector: '[data-part=item-5]', state: 'visible' } },
  { wait: 900 },
  { moveTo: '[data-part=item-3]' },
  { click: true },
  { wait: 700 },
  { assert: { selector: '[data-part=menu]', state: 'hidden' } },
  { assert: { selector: '[data-part=more][data-current]', state: 'visible' } },
  { wait: 900 },
  { moveTo: '[data-part=pick-narrow]' },
  { click: true },
  { wait: 700 },
  { assert: { selector: '[data-part=nav][data-visible="1"]', state: 'visible' } },
  { assert: { selector: '[data-part=item-1]', state: 'visible' } },
  { assert: { selector: '[data-part=item-2]', state: 'hidden' } },
  { assert: { selector: '[data-part=more][data-current]', state: 'visible' } },
  { wait: 1400 },
  { moveTo: '[data-part=pick-wide]' },
  { click: true },
  { wait: 700 },
  { assert: { selector: '[data-part=nav][data-visible="5"]', state: 'visible' } },
  { assert: { selector: '[data-part=item-3][data-current]', state: 'visible' } },
  { assert: { selector: '[data-part=more]', state: 'hidden' } },
  { wait: 900 },
]);
