import { steps } from '#src/stage/choreography.ts';

// Open, browse a category, take two glyphs without the panel closing, then search a
// name a character at a time and take the one match. Only the close control dismisses.
export default steps([
  { assert: { selector: '[data-part=picker]', state: 'hidden' } },
  { moveTo: '[data-part=trigger]' },
  { wait: 400 },
  { click: true },
  { wait: 400 },
  { assert: { selector: '[data-part=picker]', state: 'visible' } },
  { assert: { selector: '[data-part=emoji-thumbsup]', state: 'visible' } },
  { moveTo: '[data-part=cat-smileys]' },
  { wait: 350 },
  { click: true },
  { wait: 400 },
  { assert: { selector: '[data-part=cat-smileys][data-selected]', state: 'visible' } },
  { assert: { selector: '[data-part=emoji-tada]', state: 'visible' } },
  { moveTo: '[data-part=emoji-tada]' },
  { wait: 300 },
  { click: true },
  { moveTo: '[data-part=emoji-clap]' },
  { wait: 300 },
  { click: true },
  { wait: 300 },
  { assert: { selector: '[data-part=composer][data-count="2"]', state: 'visible' } },
  { assert: { selector: '[data-part=picker]', state: 'visible' } },
  { moveTo: '[data-part=search]' },
  { wait: 300 },
  { click: true },
  { type: 'wav' },
  { wait: 400 },
  { assert: { selector: '[data-part=emoji-wave]', state: 'visible' } },
  { assert: { selector: '[data-part=emoji-tada]', state: 'hidden' } },
  { moveTo: '[data-part=emoji-wave]' },
  { wait: 300 },
  { click: true },
  { wait: 300 },
  { assert: { selector: '[data-part=composer][data-count="3"]', state: 'visible' } },
  { moveTo: '[data-part=close]' },
  { wait: 350 },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=picker]', state: 'hidden' } },
  { wait: 700 },
]);
