import { steps } from '#src/stage/choreography.ts';

export default steps([
  { wait: 600 },
  // Two navigation systems in one header: the content links, and the reader's own tools.
  { assert: { selector: '[data-part=cluster][data-panel=none]', state: 'visible' } },
  { assert: { selector: '[data-part=nav-berths][data-current]', state: 'visible' } },
  { assert: { selector: '[data-part=panel]', state: 'hidden' } },
  { wait: 800 },
  { moveTo: '[data-part=util-search]' },
  { click: true },
  { wait: 700 },
  { assert: { selector: '[data-part=util-search][data-open]', state: 'visible' } },
  { assert: { selector: '[data-part=panel][data-panel=search]', state: 'visible' } },
  { assert: { selector: '[data-part=search-input]', state: 'visible' } },
  { wait: 1000 },
  // Dismissal is explicit, so the state a step reaches never depends on the state it found.
  { moveTo: '[data-part=panel-close]' },
  { click: true },
  { wait: 700 },
  { assert: { selector: '[data-part=panel]', state: 'hidden' } },
  { assert: { selector: '[data-part=cluster][data-panel=none]', state: 'visible' } },
  { wait: 800 },
  { moveTo: '[data-part=util-basket]' },
  { click: true },
  { wait: 700 },
  { assert: { selector: '[data-part=util-basket][data-open]', state: 'visible' } },
  { assert: { selector: '[data-part=panel][data-panel=basket]', state: 'visible' } },
  { wait: 1000 },
  { moveTo: '[data-part=panel-close]' },
  { click: true },
  { wait: 700 },
  { assert: { selector: '[data-part=cluster][data-panel=none]', state: 'visible' } },
  { wait: 700 },
  // The account panel is about the reader, which is what puts it in this group at all.
  { moveTo: '[data-part=util-account]' },
  { click: true },
  { wait: 700 },
  { assert: { selector: '[data-part=util-account][data-open]', state: 'visible' } },
  { assert: { selector: '[data-part=panel][data-panel=account]', state: 'visible' } },
  { assert: { selector: '[data-part=sign-out]', state: 'visible' } },
  // The content links are untouched by any of it.
  { assert: { selector: '[data-part=nav-berths][data-current]', state: 'visible' } },
  { wait: 1100 },
  { moveTo: '[data-part=panel-close]' },
  { click: true },
  { wait: 700 },
  { assert: { selector: '[data-part=panel]', state: 'hidden' } },
  { assert: { selector: '[data-part=cluster][data-panel=none]', state: 'visible' } },
  { wait: 800 },
]);
