import { steps } from '#src/stage/choreography.ts';

export default steps([
  { assert: { selector: '[data-part=state][data-state=clean]', state: 'visible' } },
  { assert: { selector: '[data-part=guard]', state: 'hidden' } },
  { moveTo: '[data-part=editor]' },
  { click: true },
  { type: ' The ramp sits a metre higher.' },
  { assert: { selector: '[data-part=state][data-state=dirty]', state: 'visible' } },
  { wait: 700 },
  { moveTo: '[data-part=back]' },
  { click: true },
  { assert: { selector: '[data-part=guard]', state: 'visible' } },
  { wait: 900 },
  { moveTo: '[data-part=keep]' },
  { click: true },
  { assert: { selector: '[data-part=guard]', state: 'hidden' } },
  { assert: { selector: '[data-part=editor]', state: 'visible' } },
  { assert: { selector: '[data-part=state][data-state=dirty]', state: 'visible' } },
  { wait: 900 },
  { moveTo: '[data-part=back]' },
  { click: true },
  { assert: { selector: '[data-part=guard]', state: 'visible' } },
  { wait: 800 },
  { moveTo: '[data-part=discard]' },
  { click: true },
  { assert: { selector: '[data-part=guard]', state: 'hidden' } },
  { assert: { selector: '[data-part=left-view]', state: 'visible' } },
  { assert: { selector: '[data-part=state][data-state=clean]', state: 'visible' } },
  { wait: 1200 },
]);
