import { steps } from '#src/stage/choreography.ts';

export default steps([
  { assert: { selector: '[data-part=wizard][data-step="1"]', state: 'visible' } },
  { assert: { selector: '[data-part=error]', state: 'hidden' } },
  // Leaving a step validates it: Next on an empty name reports, and the flow stays put.
  { moveTo: '[data-part=next]' },
  { click: true },
  { wait: 460 },
  { assert: { selector: '[data-part=error]', state: 'visible' } },
  { assert: { selector: '[data-part=wizard][data-step="1"]', state: 'visible' } },
  { wait: 800 },
  { moveTo: '[data-part=name]' },
  { type: 'Harbour' },
  { wait: 420 },
  { assert: { selector: '[data-part=error]', state: 'hidden' } },
  { moveTo: '[data-part=next]' },
  { click: true },
  { wait: 460 },
  { assert: { selector: '[data-part=wizard][data-step="2"]', state: 'visible' } },
  { wait: 500 },
  { moveTo: '[data-part=region-us]' },
  { click: true },
  { wait: 400 },
  { assert: { selector: '[data-part=region-us][aria-selected="true"]', state: 'visible' } },
  { wait: 500 },
  { moveTo: '[data-part=next]' },
  { click: true },
  { wait: 460 },
  { assert: { selector: '[data-part=review-name][data-value="Harbour"]', state: 'visible' } },
  { assert: { selector: '[data-part=review-region][data-value="us"]', state: 'visible' } },
  { wait: 800 },
  { moveTo: '[data-part=back]' },
  { click: true },
  { wait: 460 },
  // Answers are kept: coming back shows the step as it was left.
  { assert: { selector: '[data-part=wizard][data-step="2"]', state: 'visible' } },
  { assert: { selector: '[data-part=region-us][aria-selected="true"]', state: 'visible' } },
  { wait: 600 },
  { moveTo: '[data-part=next]' },
  { click: true },
  { wait: 440 },
  { moveTo: '[data-part=next]' },
  { click: true },
  { wait: 480 },
  { assert: { selector: '[data-part=wizard][data-created]', state: 'visible' } },
  { wait: 900 },
]);
