import { steps } from '#src/stage/choreography.ts';

// Two fields, two key sets, one panel. Each field raises its own keyboard and Done
// is the only thing that lowers it, so nothing here flips a state (SPEC §8).
export default steps([
  { assert: { selector: '[data-part=keyboard]', state: 'hidden' } },
  { moveTo: '[data-part=field-card]' },
  { wait: 400 },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=keyboard][data-layout=digits]', state: 'visible' } },
  { assert: { selector: '[data-part=key-4]', state: 'visible' } },
  { assert: { selector: '[data-part=key-q]', state: 'hidden' } },
  { moveTo: '[data-part=key-4]' },
  { wait: 300 },
  { click: true },
  { moveTo: '[data-part=key-2]' },
  { wait: 300 },
  { click: true },
  { wait: 300 },
  { assert: { selector: '[data-part=field-card][data-filled]', state: 'visible' } },
  { moveTo: '[data-part=next]' },
  { wait: 400 },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=keyboard][data-layout=text]', state: 'visible' } },
  { assert: { selector: '[data-part=key-q]', state: 'visible' } },
  { assert: { selector: '[data-part=key-4]', state: 'hidden' } },
  { moveTo: '[data-part=key-a]' },
  { wait: 300 },
  { click: true },
  { moveTo: '[data-part=key-d]' },
  { wait: 300 },
  { click: true },
  { wait: 300 },
  { assert: { selector: '[data-part=field-name][data-filled]', state: 'visible' } },
  { moveTo: '[data-part=done]' },
  { wait: 400 },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=keyboard]', state: 'hidden' } },
  { assert: { selector: '[data-part=pay]', state: 'visible' } },
  { wait: 800 },
]);
