import { steps } from '#src/stage/choreography.ts';

export default steps([
  { assert: { selector: '[data-part=list]', state: 'hidden' } },
  { assert: { selector: '[data-part=chip-failed]', state: 'visible' } },
  { moveTo: '[data-part=trigger]' },
  { click: true },
  { wait: 320 },
  { assert: { selector: '[data-part=list]', state: 'visible' } },
  { assert: { selector: '[data-part=trigger][aria-expanded="true"]', state: 'visible' } },
  { wait: 520 },
  { moveTo: '[data-part=opt-queued]' },
  { click: true },
  { wait: 400 },
  { assert: { selector: '[data-part=opt-queued][aria-selected="true"]', state: 'visible' } },
  { assert: { selector: '[data-part=chip-queued]', state: 'visible' } },
  // The list is still open: a control answering with a set is not finished after one pick.
  { assert: { selector: '[data-part=list]', state: 'visible' } },
  { wait: 400 },
  { moveTo: '[data-part=opt-running]' },
  { click: true },
  { wait: 400 },
  { assert: { selector: '[data-part=control][data-chosen="queued running failed"]', state: 'visible' } },
  { assert: { selector: '[data-part=chip-running]', state: 'visible' } },
  { wait: 700 },
  // Dismissal is explicit: a press outside the control puts the list away (SPEC §8).
  { moveTo: '[data-part=outside]' },
  { click: true },
  { wait: 400 },
  { assert: { selector: '[data-part=list]', state: 'hidden' } },
  { assert: { selector: '[data-part=chip-queued]', state: 'visible' } },
  { wait: 700 },
  { moveTo: '[data-part=chip-queued-remove]' },
  { click: true },
  { wait: 400 },
  { assert: { selector: '[data-part=chip-queued]', state: 'hidden' } },
  { assert: { selector: '[data-part=control][data-chosen="running failed"]', state: 'visible' } },
  { wait: 900 },
]);
