import { steps } from '#src/stage/choreography.ts';

/**
 * The three kept promises in turn, each opened by its own trigger and dismissed explicitly,
 * then the liar: the same attribute value, a different surface. No trigger toggles, so a pass
 * joined halfway proves the same thing (SPEC §8).
 */
export default steps([
  { assert: { selector: '[data-part=triggers]', state: 'visible' } },
  { assert: { selector: '[data-part=menu]', state: 'hidden' } },
  { wait: 600 },
  { moveTo: '[data-part=trig-menu]' },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=menu]', state: 'visible' } },
  { assert: { selector: '[data-part=trig-menu][aria-expanded="true"]', state: 'visible' } },
  { assert: { selector: '[data-part=opened][data-state=menu][data-match=kept]', state: 'visible' } },
  { wait: 700 },
  { moveTo: '[data-part=menu-archive]' },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=menu]', state: 'hidden' } },
  { wait: 400 },
  { moveTo: '[data-part=trig-listbox]' },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=listbox]', state: 'visible' } },
  { assert: { selector: '[data-part=opened][data-state=listbox][data-match=kept]', state: 'visible' } },
  { wait: 700 },
  { moveTo: '[data-part=opt-ie]' },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=listbox]', state: 'hidden' } },
  // The picked option sits inside the popup its pick just closed, so the trigger
  // carries the evidence.
  { assert: { selector: '[data-part=trig-listbox][data-choice=ie]', state: 'visible' } },
  { wait: 400 },
  { moveTo: '[data-part=trig-dialog]' },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=dialog]', state: 'visible' } },
  { assert: { selector: '[data-part=opened][data-state=dialog][data-match=kept]', state: 'visible' } },
  { wait: 800 },
  { moveTo: '[data-part=dialog-cancel]' },
  { click: true },
  { wait: 500 },
  { assert: { selector: '[data-part=dialog]', state: 'hidden' } },
  { wait: 500 },
  { moveTo: '[data-part=trig-lie]' },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=delete]', state: 'visible' } },
  { assert: { selector: '[data-part=announced][data-kind=menu]', state: 'visible' } },
  { assert: { selector: '[data-part=opened][data-state=dialog][data-match=broken]', state: 'visible' } },
  { assert: { selector: '[data-part=caption][data-case=broken]', state: 'visible' } },
  { wait: 1400 },
  { moveTo: '[data-part=delete-cancel]' },
  { click: true },
  { wait: 600 },
  { assert: { selector: '[data-part=delete]', state: 'hidden' } },
  { wait: 700 },
]);
